version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  allow:
    - dependency-type: "production"
    - dependency-type: "direct"
  open-pull-requests-limit: 10
